version: "3.8"
services:
    db_postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${SQL_DB_NAME}
            POSTGRES_USER: ${SQL_DB_USERNAME}
            POSTGRES_PASSWORD: ${SQL_DB_PASSWORD}
        volumes:
            - ipz_sql_data:/var/lib/postgresql/data

    db_mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: ${NoSQL_DB_NAME}
        volumes:
            - ipz_nosql_data:/data/db
            - ipz_nosql_config:/data/configdb
  
    migrate:
        image: migrate/migrate
        volumes:
            - ./migrations:/migrations
        command: [
            "-path", 
            "/migrations", 
            "-database",  
            "postgres://${SQL_DB_USERNAME}:${SQL_DB_PASSWORD}@db_postgres:5432/${SQL_DB_NAME}?sslmode=disable",
            "up"
        ]
        depends_on:
            - db_postgres
            
    server:
        image: ekedani/ipz-lab-server:2.0
        ports:
            - "80:3000"
        environment:
            MONGODB_URI: mongodb://db_mongo:27017/${NoSQL_DB_NAME}
            DB_HOST: db_postgres
            DB_PORT: 5432
            DB_DATABASE: ${SQL_DB_NAME}
            DB_USERNAME: ${SQL_DB_USERNAME}
            DB_PASSWORD: ${SQL_DB_PASSWORD}
        depends_on:
            - db_postgres
            - db_mongo
            
volumes:
    ipz_sql_data:
    ipz_nosql_data:
    ipz_nosql_config: